[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"

[functions]
  # Netlify handles bundling automatically, but we scope the 
  # external modules inside the node_bundle configuration object.
  [functions.node_bundle]
    external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true